name: GitHub-Profile-3D-Contrib

on:
  schedule: 
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Set up Git
        run: |
          git config user.name pyoja
          git config user.email wjdgns13nr@naver.com
          git remote set-url origin https://${{ secrets.TOKEN }}@github.com/${{ github.repository }}
      - name: Commit & Push
        run: |
          git add -A .
          git commit -m "generated"
          git push
